name: engineering_exercise
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter   
  
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  either_dart: ^0.1.4
  shimmer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Medium.ttf
        - asset: fonts/Raleway-SemiBold.ttf
        - asset: fonts/Raleway-Bold.ttf
        - asset: fonts/Raleway-ExtraBold.ttf
        - asset: fonts/Raleway-Black.ttf
